language: php

php: 
  - 5.3
  - 5.4

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit
