language: php

php:
  - 7.0
  - 7.1

before_script:
  - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then pecl install mongodb; fi
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install

script: vendor/bin/phpunit
